name: k8s-playground
path: .
windows:
  - name: code
    panes:
      - flex: 1
        commands:
          - command: $EDITOR
  - name: misc
    panes:
      - flex: 1
      - flex: 1
  - name: k9s
    panes:
      - commands:
          - command: sh
            args:
              - -c
              - "kind get clusters | grep -q 'k8s-playground' || kind create cluster --name k8s-playground"
          - command: kx
            args:
              - kind-k8s-playground
          - command: k9s
