# https://numtide.github.io/devshell
packages = [
  "helm-ls",
  "pyright",
  "black"
]

[[commands]]
package = "colima"

[[commands]]
name = "helm"
package = "kubernetes-helm"

[[commands]]
package = "kind"

[[commands]]
package = "kubectl"

[[commands]]
package = "tilt"
category = "kubeops"

[[commands]]
name = "kind-start"
command = '''
  COLIMA_IP=$(colima ls --json | jq -r '.address')
  kind create cluster --config=$PRJ_ROOT/kind/cluster.yaml --name=k8s-playground
  echo "The cluster IP is: ${COLIMA_IP}"
'''
category = "kubeops"
help = "Start kind cluster"

[[commands]]
name = "crds"
command = "cd $PRJ_ROOT/operator && cargo run --bin gen_crds"
category = "operator"
help = "generate crds from code"

[[commands]]
name = "run"
command = "cd $PRJ_ROOT/operator && cargo run --bin operator"
category = "operator"
help = "run operator"

[[commands]]
name = "clippy"
command = "cd $PRJ_ROOT/operator && cargo clippy"
category = "operator"
help = "run clippy"
