# https://numtide.github.io/devshell
packages = [
  "pyright"
]

[[commands]]
package = "colima"

[[commands]]
name = "helm"
package = "kubernetes-helm"

[[commands]]
package = "kind"

[[commands]]
package = "kubectl"

[[commands]]
package = "tilt"
