[package]
name = "operator"
description = "foo bar"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
k8s-openapi = { version = "0.23.0", features = ["latest"] }
kube = { version = "0.96.0", features = ["runtime", "derive"] }
serde = "1.0.215"
tokio = "1.41.1"
uuid = "1.11.0"
